---
all:
  children:
    molecule:
      hosts:
        molecule-ubuntu-24.04:
          ansible_connection: containers.podman.podman
          container_image: ubuntu:24.04
          container_command: sleep 1d
          container_privileged: false
